"""Capture the presentation's offline replay using the project's actual gateway."""
from __future__ import annotations

import json
import gc
import os
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT.parent.parent / "flower-app"))

SEQUENCE = [
    ("A", "context"), ("A", "balance"), ("B", "context"),
    ("C", "context"), ("C", "balance"), ("B", "balance"),
    ("B", "source_check"), ("A", "source_check"),
    ("B", "raw_logs"), ("B", "source_check"),
]


def capture():
    # This deck explicitly presents the packaged synthetic reduced model.
    os.environ.pop("FUSION_THERMAL_FIXTURES", None)
    from fusion_agent.thermal.core import Gateway

    with tempfile.TemporaryDirectory(prefix="fusion-presentation-") as temporary:
        gateway = Gateway(Path(temporary) / "evidence.sqlite3")
        steps = [
            {"request": {"site": site, "kind": kind}, "result": gateway.request(site, kind)}
            for site, kind in SEQUENCE
        ]
        assert steps[4]["result"]["reason"] == "analogy-not-applicable"
        assert steps[6]["result"]["finding"]["corrected_transport"] == "near-reference"
        assert steps[7]["result"]["finding"]["finding"] == "unknown"
        assert steps[8]["result"]["reason"] == "unsupported-request"
        assert steps[9]["result"]["cached"] is True
        assert steps[9]["result"]["spent"] == 5
        assert len(steps[1]["result"]["finding"]["profile_shape"]) == 11
        data = {
            "mode": "recorded-gateway-rehearsal",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "case_id": gateway.case_id,
            "source": "flower-app/fusion_agent/thermal/core.py",
            "steps": steps,
        }
        # sqlite3's context manager commits but does not close; collect finished
        # connections before TemporaryDirectory removes the database on Windows.
        gc.collect()
    (ROOT / "evidence.js").write_text(
        "// Generated by capture_evidence.py. Actual gateway outputs; no model calls.\n"
        + "window.GATEWAY_RECORDING = " + json.dumps(data, indent=2, allow_nan=False) + ";\n",
        encoding="utf-8",
    )
    print(f"Captured {len(steps)} gateway decisions: {data['case_id']}")


if __name__ == "__main__":
    capture()
