// Generated by capture_evidence.py. Actual gateway outputs; no model calls.
window.GATEWAY_RECORDING = {
  "mode": "recorded-gateway-rehearsal",
  "generated_at": "2026-10-07T16:22:56.833834+00:00",
  "case_id": "thermal-reduced-v2:7aa767b509fb86dc",
  "source": "flower-app/fusion_agent/thermal/core.py",
  "steps": [
    {
      "request": {
        "site": "A",
        "kind": "context"
      },
      "result": {
        "site": "A",
        "evidence": "context",
        "status": "released",
        "finding": {
          "balance_assumption": "verified-steady-state",
          "regime": "solved-steady-state",
          "geometry": "cylindrical",
          "subsystem": "thermal-transport",
          "field_class": "moderate-field",
          "size_class": "medium",
          "gradient_quality": "usable",
          "symptom": "weak-temperature-response"
        },
        "evidence_id": "3c75392659ec1362",
        "cost": 1,
        "spent": 1,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "A",
        "kind": "balance"
      },
      "result": {
        "site": "A",
        "evidence": "balance",
        "status": "released",
        "finding": {
          "apparent_transport": "above-reference",
          "source_basis": "assumed-command",
          "source_verified": false,
          "causal_conclusion": "not-identifiable-from-this-evidence",
          "profile_shape": [
            1.0,
            0.9,
            0.8,
            0.7,
            0.6,
            0.5,
            0.4,
            0.3,
            0.3,
            0.2,
            0.2
          ],
          "profile_radius": [
            0.0,
            0.085,
            0.17,
            0.255,
            0.34,
            0.425,
            0.51,
            0.595,
            0.68,
            0.765,
            0.85
          ],
          "profile_units": "normalised-temperature"
        },
        "evidence_id": "ec00ee94a720a932",
        "cost": 2,
        "spent": 3,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "B",
        "kind": "context"
      },
      "result": {
        "site": "B",
        "evidence": "context",
        "status": "released",
        "finding": {
          "balance_assumption": "verified-steady-state",
          "regime": "solved-steady-state",
          "geometry": "cylindrical",
          "subsystem": "thermal-transport",
          "field_class": "high-field",
          "size_class": "compact",
          "gradient_quality": "usable",
          "symptom": "weak-temperature-response"
        },
        "evidence_id": "e102449a62923566",
        "cost": 1,
        "spent": 1,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "C",
        "kind": "context"
      },
      "result": {
        "site": "C",
        "evidence": "context",
        "status": "released",
        "finding": {
          "balance_assumption": "verified-steady-state",
          "regime": "solved-steady-state",
          "geometry": "cylindrical",
          "subsystem": "thermal-transport",
          "field_class": "moderate-field",
          "size_class": "compact",
          "gradient_quality": "insufficient",
          "symptom": "flat-temperature-profile"
        },
        "evidence_id": "5ab5d33c6dc4fe8a",
        "cost": 1,
        "spent": 1,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "C",
        "kind": "balance"
      },
      "result": {
        "site": "C",
        "evidence": "balance",
        "status": "denied",
        "reason": "analogy-not-applicable",
        "spent": 1,
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "B",
        "kind": "balance"
      },
      "result": {
        "site": "B",
        "evidence": "balance",
        "status": "released",
        "finding": {
          "apparent_transport": "above-reference",
          "source_basis": "assumed-command",
          "source_verified": false,
          "causal_conclusion": "not-identifiable-from-this-evidence",
          "profile_shape": [
            1.0,
            0.9,
            0.9,
            0.8,
            0.7,
            0.6,
            0.5,
            0.5,
            0.4,
            0.4,
            0.3
          ],
          "profile_radius": [
            0.0,
            0.085,
            0.17,
            0.255,
            0.34,
            0.425,
            0.51,
            0.595,
            0.68,
            0.765,
            0.85
          ],
          "profile_units": "normalised-temperature"
        },
        "evidence_id": "6e4b44d942e2ab7f",
        "cost": 2,
        "spent": 3,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "B",
        "kind": "source_check"
      },
      "result": {
        "site": "B",
        "evidence": "source_check",
        "status": "released",
        "finding": {
          "independent_audit_available": true,
          "finding": "delivered-below-assumed",
          "corrected_transport": "near-reference"
        },
        "evidence_id": "c60a84c3dfe0e4d6",
        "cost": 2,
        "spent": 5,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "A",
        "kind": "source_check"
      },
      "result": {
        "site": "A",
        "evidence": "source_check",
        "status": "released",
        "finding": {
          "independent_audit_available": false,
          "finding": "unknown",
          "corrected_transport": "not-computed"
        },
        "evidence_id": "748bdcc26670927a",
        "cost": 2,
        "spent": 5,
        "allowance": 5,
        "cached": false,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "B",
        "kind": "raw_logs"
      },
      "result": {
        "status": "denied",
        "reason": "unsupported-request",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    },
    {
      "request": {
        "site": "B",
        "kind": "source_check"
      },
      "result": {
        "site": "B",
        "evidence": "source_check",
        "status": "released",
        "finding": {
          "independent_audit_available": true,
          "finding": "delivered-below-assumed",
          "corrected_transport": "near-reference"
        },
        "evidence_id": "c60a84c3dfe0e4d6",
        "cost": 2,
        "spent": 5,
        "allowance": 5,
        "cached": true,
        "provenance": "reduced-1d-transport-v1",
        "case_id": "thermal-reduced-v2:7aa767b509fb86dc"
      }
    }
  ]
};
